# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('teste', ['core'])
    module.source = [
        'model/teste.cc',
        'helper/teste-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('teste')
    module_test.source = [
        'test/teste-test-suite.cc',
        ]

    headers = bld.new_task_gen(features=['ns3header'])
    headers.module = 'teste'
    headers.source = [
        'model/teste.h',
        'helper/teste-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.add_subdirs('examples')

    # bld.ns3_python_bindings()

