# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('aid', ['internet', 'config-store', 'tools'])
    module.source = [
        'model/aid.cc',
		'model/aid-header.cc',
		'model/aid-neighbor.cc',
		'model/vector2d.cc',
        'helper/aid-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('aid')
    module_test.source = [
        'test/aid-test-suite.cc',
        ]

    headers = bld.new_task_gen(features=['ns3header'])
    headers.module = 'aid'
    headers.source = [
        'model/aid.h',
		'model/aid-header.h',
		'model/aid-neighbor.h',
		'model/vector2d.h',
		'model/link-life-time.h',
        'helper/aid-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.add_subdirs('examples')

    # bld.ns3_python_bindings()

